version: '3'

networks:
  monitor:
    driver: bridge

services:
  prometheus:
    image: prom/prometheus:latest
    hostname: prometheus
    volumes:
      - ./config.yaml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - monitor

  grafana:
    image: grafana/grafana-enterprise:9.0.3
    hostname: grafana
    ports:
      - "3000:3000"
    networks:
      - monitor

